# Site settings
title: RI NEMBA
email: alex@goldenmeanie.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rinemba.org" # the base hostname & protocol for your site

permalink: article/:title
